// ==========================================
// MOCK DATA - JavaScript Format
// ==========================================

// Mock Users
const mockUsers = [
  {
    id: 'admin-1',
    email: 'admin@university.edu',
    password: 'admin123',
    role: 'admin',
    firstName: 'John',
    lastName: 'Administrator',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: 'teacher-1',
    email: 'sarah.johnson@university.edu',
    password: 'teacher123',
    role: 'teacher',
    firstName: 'Sarah',
    lastName: 'Johnson',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'teacher-2',
    email: 'michael.brown@university.edu',
    password: 'teacher123',
    role: 'teacher',
    firstName: 'Michael',
    lastName: 'Brown',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'teacher-3',
    email: 'emily.davis@university.edu',
    password: 'teacher123',
    role: 'teacher',
    firstName: 'Emily',
    lastName: 'Davis',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'student-1',
    email: 'david.wilson@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'David',
    lastName: 'Wilson',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'student-2',
    email: 'emma.garcia@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'Emma',
    lastName: 'Garcia',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'student-3',
    email: 'james.martinez@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'James',
    lastName: 'Martinez',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'student-4',
    email: 'olivia.anderson@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'Olivia',
    lastName: 'Anderson',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'student-5',
    email: 'william.thomas@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'William',
    lastName: 'Thomas',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
];

const mockTeachers = [
  {
    id: 'teacher-1',
    email: 'sarah.johnson@university.edu',
    password: 'teacher123',
    role: 'teacher',
    firstName: 'Sarah',
    lastName: 'Johnson',
    department: 'Computer Science',
    employeeId: 'T001',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'teacher-2',
    email: 'michael.brown@university.edu',
    password: 'teacher123',
    role: 'teacher',
    firstName: 'Michael',
    lastName: 'Brown',
    department: 'Mathematics',
    employeeId: 'T002',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'teacher-3',
    email: 'emily.davis@university.edu',
    password: 'teacher123',
    role: 'teacher',
    firstName: 'Emily',
    lastName: 'Davis',
    department: 'Physics',
    employeeId: 'T003',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
];

const mockStudents = [
  {
    id: 'student-1',
    email: 'david.wilson@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'David',
    lastName: 'Wilson',
    studentId: 'S2024001',
    enrollmentYear: 2024,
    program: 'Computer Science',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'student-2',
    email: 'emma.garcia@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'Emma',
    lastName: 'Garcia',
    studentId: 'S2024002',
    enrollmentYear: 2024,
    program: 'Computer Science',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'student-3',
    email: 'james.martinez@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'James',
    lastName: 'Martinez',
    studentId: 'S2024003',
    enrollmentYear: 2024,
    program: 'Mathematics',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'student-4',
    email: 'olivia.anderson@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'Olivia',
    lastName: 'Anderson',
    studentId: 'S2024004',
    enrollmentYear: 2024,
    program: 'Computer Science',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: 'student-5',
    email: 'william.thomas@student.edu',
    password: 'student123',
    role: 'student',
    firstName: 'William',
    lastName: 'Thomas',
    studentId: 'S2024005',
    enrollmentYear: 2024,
    program: 'Physics',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
];

// Mock Courses
const mockCourses = [
  {
    id: 'course-1',
    code: 'CS101',
    name: 'Introduction to Programming',
    description: 'Learn the fundamentals of programming using Python',
    credits: 3,
    teacherId: 'teacher-1',
    semester: 'Fall',
    academicYear: '2024-2025',
    createdAt: new Date('2024-08-01'),
  },
  {
    id: 'course-2',
    code: 'CS201',
    name: 'Data Structures and Algorithms',
    description: 'Advanced data structures and algorithm design',
    credits: 4,
    teacherId: 'teacher-1',
    semester: 'Fall',
    academicYear: '2024-2025',
    createdAt: new Date('2024-08-01'),
  },
  {
    id: 'course-3',
    code: 'MATH201',
    name: 'Linear Algebra',
    description: 'Vectors, matrices, and linear transformations',
    credits: 3,
    teacherId: 'teacher-2',
    semester: 'Fall',
    academicYear: '2024-2025',
    createdAt: new Date('2024-08-01'),
  },
  {
    id: 'course-4',
    code: 'PHY101',
    name: 'Physics I',
    description: 'Classical mechanics and thermodynamics',
    credits: 4,
    teacherId: 'teacher-3',
    semester: 'Fall',
    academicYear: '2024-2025',
    createdAt: new Date('2024-08-01'),
  },
  {
    id: 'course-5',
    code: 'CS301',
    name: 'Database Systems',
    description: 'Database design, SQL, and NoSQL databases',
    credits: 3,
    teacherId: 'teacher-1',
    semester: 'Spring',
    academicYear: '2024-2025',
    createdAt: new Date('2024-08-01'),
  },
];

// Mock Enrollments
const mockEnrollments = [
  { id: 'enr-1', studentId: 'student-1', courseId: 'course-1', enrolledAt: new Date('2024-08-15'), status: 'active' },
  { id: 'enr-2', studentId: 'student-1', courseId: 'course-2', enrolledAt: new Date('2024-08-15'), status: 'active' },
  { id: 'enr-3', studentId: 'student-1', courseId: 'course-3', enrolledAt: new Date('2024-08-15'), status: 'active' },
  { id: 'enr-4', studentId: 'student-2', courseId: 'course-1', enrolledAt: new Date('2024-08-15'), status: 'active' },
  { id: 'enr-5', studentId: 'student-2', courseId: 'course-2', enrolledAt: new Date('2024-08-15'), status: 'active' },
  { id: 'enr-6', studentId: 'student-3', courseId: 'course-3', enrolledAt: new Date('2024-08-15'), status: 'active' },
  { id: 'enr-7', studentId: 'student-4', courseId: 'course-1', enrolledAt: new Date('2024-08-15'), status: 'active' },
  { id: 'enr-8', studentId: 'student-4', courseId: 'course-4', enrolledAt: new Date('2024-08-15'), status: 'active' },
  { id: 'enr-9', studentId: 'student-5', courseId: 'course-4', enrolledAt: new Date('2024-08-15'), status: 'active' },
];

// Mock Assessments
const mockAssessments = [
  {
    id: 'assess-1',
    courseId: 'course-1',
    name: 'Assignment 1',
    type: 'assignment',
    maxMarks: 20,
    weightage: 10,
    date: new Date('2024-09-15'),
  },
  {
    id: 'assess-2',
    courseId: 'course-1',
    name: 'Midterm Exam',
    type: 'midterm',
    maxMarks: 50,
    weightage: 30,
    date: new Date('2024-10-15'),
  },
  {
    id: 'assess-3',
    courseId: 'course-1',
    name: 'Final Exam',
    type: 'final',
    maxMarks: 100,
    weightage: 50,
    date: new Date('2024-12-10'),
  },
  {
    id: 'assess-4',
    courseId: 'course-2',
    name: 'Quiz 1',
    type: 'quiz',
    maxMarks: 10,
    weightage: 10,
    date: new Date('2024-09-20'),
  },
  {
    id: 'assess-5',
    courseId: 'course-2',
    name: 'Midterm Exam',
    type: 'midterm',
    maxMarks: 50,
    weightage: 40,
    date: new Date('2024-10-20'),
  },
  {
    id: 'assess-6',
    courseId: 'course-3',
    name: 'Assignment 1',
    type: 'assignment',
    maxMarks: 25,
    weightage: 15,
    date: new Date('2024-09-10'),
  },
];

// Mock Results
const mockResults = [
  { id: 'res-1', assessmentId: 'assess-1', studentId: 'student-1', marksObtained: 18, uploadedAt: new Date('2024-09-20') },
  { id: 'res-2', assessmentId: 'assess-2', studentId: 'student-1', marksObtained: 42, uploadedAt: new Date('2024-10-20') },
  { id: 'res-3', assessmentId: 'assess-3', studentId: 'student-1', marksObtained: 85, uploadedAt: new Date('2024-12-15') },
  { id: 'res-4', assessmentId: 'assess-4', studentId: 'student-1', marksObtained: 9, uploadedAt: new Date('2024-09-25') },
  { id: 'res-5', assessmentId: 'assess-5', studentId: 'student-1', marksObtained: 45, uploadedAt: new Date('2024-10-25') },
  { id: 'res-6', assessmentId: 'assess-6', studentId: 'student-1', marksObtained: 22, uploadedAt: new Date('2024-09-15') },
  { id: 'res-7', assessmentId: 'assess-1', studentId: 'student-2', marksObtained: 19, uploadedAt: new Date('2024-09-20') },
  { id: 'res-8', assessmentId: 'assess-1', studentId: 'student-4', marksObtained: 17, uploadedAt: new Date('2024-09-20') },
];

// Mock Attendance Records
const mockAttendance = [
  // Course 1 - Student 1
  { id: 'att-1', courseId: 'course-1', studentId: 'student-1', date: new Date('2024-09-01'), status: 'present' },
  { id: 'att-2', courseId: 'course-1', studentId: 'student-1', date: new Date('2024-09-03'), status: 'present' },
  { id: 'att-3', courseId: 'course-1', studentId: 'student-1', date: new Date('2024-09-05'), status: 'present' },
  { id: 'att-4', courseId: 'course-1', studentId: 'student-1', date: new Date('2024-09-08'), status: 'absent' },
  { id: 'att-5', courseId: 'course-1', studentId: 'student-1', date: new Date('2024-09-10'), status: 'present' },
  { id: 'att-6', courseId: 'course-1', studentId: 'student-1', date: new Date('2024-09-12'), status: 'late' },
  { id: 'att-7', courseId: 'course-1', studentId: 'student-1', date: new Date('2024-09-15'), status: 'present' },
  { id: 'att-8', courseId: 'course-1', studentId: 'student-1', date: new Date('2024-09-17'), status: 'present' },
  
  // Course 1 - Student 2
  { id: 'att-9', courseId: 'course-1', studentId: 'student-2', date: new Date('2024-09-01'), status: 'present' },
  { id: 'att-10', courseId: 'course-1', studentId: 'student-2', date: new Date('2024-09-03'), status: 'present' },
  { id: 'att-11', courseId: 'course-1', studentId: 'student-2', date: new Date('2024-09-05'), status: 'absent' },
  { id: 'att-12', courseId: 'course-1', studentId: 'student-2', date: new Date('2024-09-08'), status: 'present' },
  
  // Course 2 - Student 1
  { id: 'att-13', courseId: 'course-2', studentId: 'student-1', date: new Date('2024-09-02'), status: 'present' },
  { id: 'att-14', courseId: 'course-2', studentId: 'student-1', date: new Date('2024-09-04'), status: 'present' },
  { id: 'att-15', courseId: 'course-2', studentId: 'student-1', date: new Date('2024-09-06'), status: 'present' },
  { id: 'att-16', courseId: 'course-2', studentId: 'student-1', date: new Date('2024-09-09'), status: 'present' },
  { id: 'att-17', courseId: 'course-2', studentId: 'student-1', date: new Date('2024-09-11'), status: 'absent' },
  
  // Course 3 - Student 1
  { id: 'att-18', courseId: 'course-3', studentId: 'student-1', date: new Date('2024-09-01'), status: 'present' },
  { id: 'att-19', courseId: 'course-3', studentId: 'student-1', date: new Date('2024-09-03'), status: 'present' },
  { id: 'att-20', courseId: 'course-3', studentId: 'student-1', date: new Date('2024-09-05'), status: 'present' },
];

// Mock System Settings
const mockSettings = {
  siteName: 'University Student Portal',
  academicYear: '2024-2025',
  currentSemester: 'Fall 2024',
  minimumAttendance: 75,
  passingGrade: 40,
  emailNotifications: true,
};
